# Generated by Django 6.0 on 2025-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('professional', 'Professional'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
