# Generated by Django 6.0 on 2025-12-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='languages',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='location',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='sessions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
