# Generated by Django 6.0 on 2025-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
