# Generated by Django 6.0 on 2025-12-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_professionalprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('chat', 'Chat')], default='video', max_length=10),
        ),
    ]
