# Generated by Django 6.0 on 2026-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_professionalprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='rejection_reason_type',
            field=models.CharField(blank=True, choices=[('invalid_id', 'Invalid or Expired ID'), ('unclear_certificates', 'Unclear or Missing Certificates'), ('fake_profile', 'Potential Fake Profile / Identity Issue'), ('insufficient_bio', 'Incomplete or Low Quality Bio'), ('other', 'Other (View/Edit Below)')], max_length=50, null=True, verbose_name='Reason Category'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Detailed Feedback'),
        ),
    ]
