# Generated by Django 6.0 on 2026-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_professionalprofile_rejection_reason_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'International Passport'), ('national_id', 'National ID Card'), ('driver_license', "Driver's License"), ('professional_id', 'Professional ID / License')], max_length=50, null=True),
        ),
    ]
