# Generated by Django 6.0 on 2026-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_professionalprofile_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='id_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
