# Generated by Django 6.0 on 2026-01-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_professionalprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'International Passport'), ('national_id', 'National ID Card'), ('driver_license', "Driver's License")], max_length=50, null=True),
        ),
    ]
