"""
Django settings for soultalk_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
# Load .env file
env_path = os.path.join(BASE_DIR, '.env')
if not os.path.exists(env_path):
    # Check parent directory (project root)
    env_path = os.path.join(BASE_DIR.parent, '.env')
load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-62pn@we=oy!+50pl=d&oj066j9f*2=9-5b132g=h9^(&s*@f#^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'accounts',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'soultalk_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'soultalk_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

default_db = dj_database_url.config(
    default=os.getenv('DATABASE_URL', 'postgresql://zube@localhost:5432/soultalk_db'),
    conn_max_age=600,
    conn_health_checks=True,
)
default_db['ATOMIC_REQUESTS'] = True

DATABASES = {
    'default': default_db
}





# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Cloud Storage Settings (Supabase S3)
# Set USE_S3=True in your environment to enable persistent storage
USE_S3 = os.getenv('USE_S3', 'True') == 'True'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'profiles')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-west-2')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN') # Optional
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_QUERYSTRING_AUTH = False
    
    # This ensures that URLs generated by Django use the S3 endpoint
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # If using custom domain for images
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    else:
        # For Supabase, URLs usually look like [endpoint]/[bucket]/[path]
        # S3Boto3Storage handles this automatically if endpoint is set.
        pass
else:
    # Local storage fallback
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CORS_ALLOW_ALL_ORIGINS = True
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Supabase Settings
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')


# ZegoCloud Settings
ZEGO_APP_ID = os.getenv('ZEGO_APP_ID')

ZEGO_SERVER_SECRET = os.getenv('ZEGO_SERVER_SECRET')
CHAPA_SECRET_KEY = os.getenv('CHAPA_SECRET_KEY')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

JAZZMIN_SETTINGS = {
    "site_title": "SoulTalk Admin",
    "site_header": "SoulTalk",
    "site_brand": "SoulTalk Management",
    "site_logo": None,
    "welcome_sign": "Welcome back to SoulTalk Panel",
    "copyright": "SoulTalk Ltd 2026",
    "search_model": ["accounts.User"],
    "user_avatar": "profile_photo",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": ["accounts.AdminUser"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.User": "fas fa-user-circle",
        "accounts.Professional": "fas fa-user-md",
        "accounts.Client": "fas fa-user-friends",
        "accounts.ProfessionalProfile": "fas fa-id-card",
        "accounts.ClientProfile": "fas fa-address-book",
    },
    "order_with_respect_to": ["accounts", "auth"],
    "colorscheme": "theme-teal",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_CONFIG = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-teal",
    "navbar": "navbar-teal navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_remove_offset": False,
    "sidebar_link_nav_small_text": False,
    "footer_link_nav_small_text": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-teal",
        "secondary": "btn-outline-secondary",
        "info": "btn-secondary text-white",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "custom_css": """
        /* Force Hide Add and Change buttons on Dashboard */
        .card-body td .btn-success, 
        .card-body td .btn-info,
        .card-body td .btn-primary,
        .addlink, .changelink, .add-link, .change-link { 
            display: none !important; 
        }

        /* Change Circle Logo 'A' to 'ST' */
        .brand-link .brand-image { display: none !important; }
        .brand-link::before {
            content: "ST";
            background: #25A8A0;
            color: white;
            padding: 5px 8px;
            border-radius: 50%;
            font-weight: 900;
            font-size: 14px;
            margin-right: 10px;
            margin-left: 5px;
            display: inline-block;
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }
        
        /* Remove Red Stars (Required Fields) */
        .required label::after, label.required::after { content: "" !important; display: none !important; }
        
        /* Centralized & Widened Search Bar */
        .navbar-nav.ml-auto { width: 100% !important; display: flex !important; justify-content: center !important; }
        #search-form { width: 60% !important; margin: 0 auto !important; }
        #search-form .input-group { width: 100% !important; }
        #search-form input { 
            border-radius: 25px !important; 
            padding: 12px 25px !important; 
            background: rgba(255,255,255,0.1) !important;
            border: 1px solid rgba(255,255,255,0.2) !important;
            color: white !important;
            font-size: 15px !important;
        }
        
        /* Premium Dashboard Card Headers */
        .card-header { background-color: rgba(37, 168, 160, 0.05) !important; border-bottom: none !important; }
        .card-title { font-weight: 800 !important; color: #1e8a82; text-transform: uppercase; letter-spacing: 1px; }

        /* Unified & Attractive File/Image Upload UI */
        .file-upload { 
            border: 2px dashed #25A8A0 !important; 
            background: #fafafa !important;
            border-radius: 12px !important;
            padding: 25px !important;
            text-align: center !important;
            position: relative;
            display: block;
            width: 100%;
            transition: all 0.3s ease;
        }
        .file-upload:hover { 
            background: #f0fdfc !important;
            border-color: #1e8a82 !important;
        }
        /* Hide complex 'Currently/Change' text */
        .file-upload { color: transparent !important; font-size: 0 !important; }
        .file-upload::before {
            content: "Click to upload or drag & drop";
            color: #666;
            font-size: 14px;
            font-weight: 600;
            display: block;
            margin-bottom: 10px;
        }
        .file-upload a { 
            color: #25A8A0 !important; 
            font-size: 13px !important; 
            font-weight: 700 !important;
            text-decoration: none !important;
            display: inline-block !important;
            margin-bottom: 15px !important;
            background: white;
            padding: 5px 12px;
            border-radius: 6px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }
        .file-upload a::before { content: "📄 View Current: "; color: #999; font-weight: 400; }
        .file-upload input[type="file"] { 
            color: #333 !important; 
            font-size: 13px !important;
            margin: 0 auto !important;
            display: block !important;
        }
        
        /* Hide boilerplate Clear labels */
        .file-upload br, .file-upload span.clearable-file-input { display: none !important; }
    """,
    "custom_js": """
        document.addEventListener('DOMContentLoaded', function() {
            const statusField = document.querySelector('#id_professional_profile-0-verification_status');
            const reasonTypeRow = document.querySelector('.field-rejection_reason_type');

            if (statusField && reasonTypeRow) {
                function toggleRejectionFields() {
                    if (statusField.value === 'rejected') {
                        reasonTypeRow.style.display = 'block';
                    } else {
                        reasonTypeRow.style.display = 'none';
                    }
                }

                statusField.addEventListener('change', toggleRejectionFields);
                toggleRejectionFields();
            }
        });
    """
}
